name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout Repository
          
    - name: Create symbolic link for Makefile
      run: ln -s Makefile.Linux Makefile
      
    - name: Build Project
      run: make
